version: 0.0
os: linux
files: 
  source: /
  destination: /home/ec2-user/cicd2
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user

permissions:
- object: /home/ec2-user
  pattern: "**"
  owner: ec2-user
  group: ec2-user
  mode: 664
  type:
    - file

- object: /home/ec2-user
  pattern: "**"
  owner: ec2-user
  group: ec2-user
  mode: 755
  type:
  - directory
  