name: deploy
on:
  workflow_run: 
    workflows: ["Pylint","pytest"]
    types:
      - completed




jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: remote-ssh
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 43.200.70.100
        username: ec2-user
        key: ${{ secrets.KEY }}
        port: 22
        script: whoami
